apiVersion: batch/v1
kind: Job
metadata:
  name: model-builder-job
  namespace: mlops
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 900
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: default

      # 1️⃣ Init‑container: install MLflow & build the workspace
      initContainers:
      - name: generate-build-context
        image: python:3.10-slim
        command: ["sh", "-c"]
        args:
          - |
            set -ex
            pip install mlflow==2.14.3 mlserver mlserver-mlflow boto3
            mlflow models generate-dockerfile \
              -m "runs:/<RUN_ID_PLACEHOLDER>/model" \
              -d /workspace \
              --enable-mlserver
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000"
        envFrom:
        - secretRef:
            name: aws-s3-credentials
        volumeMounts:
        - name: build-context
          mountPath: /workspace

      # 2️⃣ Kaniko container: build & push the final image
      containers:
      - name: kaniko-builder
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--context=dir:///workspace"
          - "--dockerfile=/workspace/Dockerfile"
          - "--destination=<DOCKER_IMAGE_NAME_PLACEHOLDER>"
        env:
        - name: DOCKER_CONFIG
          value: "/kaniko/.docker"
        volumeMounts:
        - name: build-context
          mountPath: /workspace
        - name: docker-config
          mountPath: /kaniko/.docker

      restartPolicy: OnFailure

      # Shared volumes
      volumes:
      - name: build-context
        emptyDir: {}
      - name: docker-config
        secret:
          secretName: dockerhub-creds
          items:
          - key: .dockerconfigjson
            path: config.json
