apiVersion: batch/v1
kind: Job
metadata:
  name: model-builder-job
  namespace: mlops
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      # Service account linked to the Docker Hub credentials secret
      serviceAccountName: default
      initContainers:
      - name: generate-build-context
        image: python:3.10-slim
        command:
        - "sh"
        - "-c"
        - |
          set -ex
          pip install "mlflow[mlserver]==2.14.3" boto3
          # Generate the Dockerfile and model artifacts into the shared workspace
          mlflow models generate-dockerfile \
            -m "runs:/${RUN_ID}/model" \
            -d /workspace \
            --enable-mlserver
          echo "Build context generated successfully."
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000"
        envFrom:
        - secretRef:
            name: aws-s3-credentials
        volumeMounts:
        - name: build-context
          mountPath: /workspace
      containers:
      - name: kaniko-builder
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--context=dir:///workspace"
          - "--dockerfile=/workspace/Dockerfile"
          - "--destination=<DOCKER_IMAGE_NAME_PLACEHOLDER>"
        env:
        - name: DOCKER_IMAGE_NAME
          value: "<DOCKER_IMAGE_NAME_PLACEHOLDER>"
        - name: DOCKER_CONFIG
          value: "/kaniko/.docker"
        volumeMounts:
        - name: build-context
          mountPath: /workspace
        - name: docker-config
          mountPath: /kaniko/.docker
      volumes:
      # Shared temporary volume for the initContainer to pass files to Kaniko
      - name: build-context
        emptyDir: {}
      # Secret containing Docker Hub credentials for Kaniko push
      - name: docker-config
        secret:
          secretName: dockerhub-creds
      restartPolicy: OnFailure
  backoffLimit: 1
  activeDeadlineSeconds: 900
