# This manifest defines a Kubernetes Job to run the model training scripts.
apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
  namespace: mlops
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
      - name: wait-for-mlflow
        image: busybox:1.36
        command: ["sh", "-c", "echo 'Waiting for MLflow...' && until nc -z -w 5 mlflow 5000; do sleep 5; done && echo 'MLflow is ready!'"]
      containers:
      - name: trainer
        image: mrweasel99/mlops-trainer:latest
        command:
          - "sh"
          - "-c"
          - |
            set -ex
            echo "--- Running hyperparameter tuning ---"
            python /scripts/hyperparameter_tuning.py
            # THIS IS THE FIX: The "echo 'Training complete'" line has been removed
            # to ensure the run ID is the last line of output.
        envFrom:
        - secretRef:
            name: aws-s3-credentials
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000"
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
      volumes:
      - name: scripts-volume
        configMap:
          name: training-scripts
      restartPolicy: OnFailure
  backoffLimit: 1
  activeDeadlineSeconds: 300
