# This manifest defines a Kubernetes Job to run the model training scripts.
apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
  namespace: mlops
spec:
  template:
    metadata:
      # This annotation tells Istio not to inject its sidecar proxy.
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
      - name: setup-environment
        # The busybox image contains the 'nc' (netcat) utility
        image: busybox:1.36
        command:
          - "sh"
          - "-c"
          - |
            set -ex
            echo "Waiting for MLflow service to be ready..."
            # THIS IS THE FIX: Use netcat (nc) to check if the port is open, which is more reliable
            # than checking for a specific HTTP path that may not exist.
            until nc -z -w 5 mlflow 5000; do
              echo "MLflow service not reachable yet, sleeping for 5 seconds..."
              sleep 5
            done
            echo "MLflow is ready!"

            # The MinIO setup part is removed as it's now handled by the Deploy MLOps stage.
            # If needed, it could be a separate initContainer using minio/mc.
      containers:
      - name: trainer
        image: python:3.10-slim
        command:
          - "sh"
          - "-c"
          - |
            set -ex
            # Add boto3 to the list of installed packages.
            pip install "mlflow[mlserver]==2.14.3" scikit-learn boto3
            echo "--- Running hyperparameter tuning ---"
            python /scripts/hyperparameter_tuning.py
            echo "--- Training complete ---"
        envFrom:
        - secretRef:
            name: aws-s3-credentials
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000"
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
      volumes:
      - name: scripts-volume
        configMap:
          name: training-scripts
      restartPolicy: OnFailure
  backoffLimit: 1
  activeDeadlineSeconds: 300
