# services/traefik/values.yaml
resources:  # <--- Add this block here
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "500m"

dashboard:  # <--- Keep existing below
  enabled: true
  ingressRoute:
    enabled: true

metrics:
  prometheus:
    enabled: true

nodeSelector:
  kubernetes.io/hostname: mlops-master

service:
  type: NodePort

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    nodePort: 32255
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    nodePort: 30594