dashboard:
  enabled: true
  ingressRoute:
    enabled: true

metrics:
  prometheus:
    enabled: true

nodeSelector:
  kubernetes.io/hostname: mlops-master

service:
  type: NodePort
  ports:
    web:
      port: 80
      targetPort: 8000
      nodePort: 32255
    websecure:
      port: 443
      targetPort: 8443
      nodePort: 30594
