apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops
spec:
  type: ClusterIP
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: mlflow/mlflow:2.12.2     # fixed tag
          imagePullPolicy: IfNotPresent
          args:
            - server
            - --host
            - "0.0.0.0"
            - --backend-store-uri
            - postgresql://mlflow:${POSTGRES_PASSWORD}@postgresql.mlops.svc.cluster.local:5432/mlflow
            - --default-artifact-root
            - s3://minio/mlflow-artifacts
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: minio-credentials
