apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bucket-setup
  namespace: mlops
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
      - name: wait-for-minio
        image: busybox:1.36
        command: ["sh", "-c", "echo 'Waiting for MinIO...' && until nc -z -w 5 minio 9000; do sleep 5; done && echo 'MinIO is ready!'"]
      containers:
      - name: mc-container
        image: minio/mc
        command:
          - "sh"
          - "-c"
          - |
            set -ex
            mc alias set minio-cluster http://minio:9000 $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
            mc mb minio-cluster/mlflow-artifacts || echo "Bucket 'mlflow-artifacts' already exists."
            mc policy set readwrite minio-cluster/mlflow-artifacts
            echo "MinIO setup complete."
        envFrom:
        - secretRef:
            name: aws-s3-credentials
      restartPolicy: OnFailure
  backoffLimit: 2
  activeDeadlineSeconds: 120
