# This manifest defines a Kubernetes Job to create the 'mlflow-artifacts' bucket.
# Using a Job is the correct approach for a task that runs once to completion.
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bucket-setup
  namespace: mlops
spec:
  # The 'template' field describes the pod that the Job will create.
  template:
    metadata:
      # This annotation tells Istio not to inject its sidecar
      # proxy into the pod created by this Job.
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      # The initContainer waits for the MinIO service to be fully healthy
      # before the main container starts. This prevents connection errors.
      initContainers:
      - name: wait-for-minio
        image: busybox:1.36
        command:
          - "sh"
          - "-c"
          - |
            echo "Waiting for MinIO service to be ready..."
            until wget -q --spider -T 10 http://minio:9000/minio/health/live; do
              echo "MinIO not ready yet, sleeping for 5 seconds..."
              sleep 5
            done
            echo "MinIO is ready! Proceeding with bucket setup."
      containers:
      - name: mc-container
        image: minio/mc
        command:
          - "sh"
          - "-c"
          - |
            set -ex
            # Use credentials loaded from the secret to configure the client
            mc alias set minio-cluster http://minio:9000 $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
            
            # Create the bucket, ignoring the error if it already exists
            mc mb minio-cluster/mlflow-artifacts || echo "Bucket 'mlflow-artifacts' already exists."
            
            # Set a public-read policy so MLflow can easily access artifacts
            mc policy set download minio-cluster/mlflow-artifacts
            
            echo "MinIO setup complete."
        envFrom:
        - secretRef:
            name: aws-s3-credentials
      restartPolicy: OnFailure
  # These settings ensure the job doesn't run for too long.
  backoffLimit: 2
  activeDeadlineSeconds: 120
