    # services/minio/minio-ingress.yaml
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: minio-console-ingress
      namespace: mlops
      annotations:
        # This annotation tells NGINX to rewrite the path, stripping /minio
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        # Set ingress class for NGINX controller
        kubernetes.io/ingress.class: nginx # Older versions use this; ingressClassName is preferred
    spec:
      ingressClassName: nginx # Explicitly use the NGINX Ingress Controller
      rules:
      - http:
          paths:
          - path: /minio/(.*) # Capture everything after /minio
            pathType: Prefix # Use Prefix for path matching
            backend:
              service:
                name: minio-console # Target the MinIO console service
                port:
                  number: 9090      # MinIO console's actual port
    