# minio/values.yaml (Modified)
rootUser: "${MINIO_ROOT_USER}"
rootPassword: "${MINIO_ROOT_PASSWORD}"

# persistence on the new default local-path StorageClass
persistence:
  enabled: true
  storageClass: local-path
  size: 10Gi

service:
  type: ClusterIP

console:
  enabled: true
  service:
    port: 9090 # Ensure this matches your minio-console service's actual port

# Add this section to set the environment variable
extraEnvVars:
  - name: MINIO_BROWSER_REDIRECT_URL
    value: "http://34.118.28.157:32255/minio" # <--- IMPORTANT: Set this to your external Traefik URL + IngressRoute path