# minio/values.yaml (Modified - remove extraEnvVars)
rootUser: "${MINIO_ROOT_USER}"
rootPassword: "${MINIO_ROOT_PASSWORD}"

# persistence on the new default local-path StorageClass
persistence:
  enabled: true
  storageClass: local-path
  size: 10Gi

service:
  type: ClusterIP

console:
  enabled: true
  service:
    port: 9090 # Ensure this matches your minio-console service's actual port
# The extraEnvVars section for MINIO_BROWSER_REDIRECT_URL is removed here
