# services/kserve/inference-service.yaml

apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mlflow-wine-classifier
  namespace: mlops
  annotations:
    autoscaling.knative.dev/initial-scale: "1"
    serving.kserve.io/enable-prometheus-scraping: "true" # <-- ADD THIS LINE
spec:
  predictor:
    minReplicas: 1
    imagePullSecrets:
      - name: dockerhub-creds
    containers:
    - name: mlflow-wine-classifier
      image: <DOCKER_IMAGE_NAME>
      env:
      - name: PROTOCOL
        value: v2
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"