apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mlflow-wine-classifier
  namespace: mlops
  annotations:
    autoscaling.knative.dev/initial-scale: "1"   # ▶️  start with one Pod
spec:
  predictor:
    minReplicas: 1                               # ▶️  keep one running
    imagePullSecrets:
      - name: dockerhub-creds
    containers:
    - name: mlflow-wine-classifier
      image: <DOCKER_IMAGE_NAME>                 # Jenkins replaces this
      env:
      - name: PROTOCOL
        value: v2
