apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mlflow-wine-classifier
  namespace: mlops
  annotations:
    autoscaling.knative.dev/initial-scale: "1"
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    minReplicas: 1
    containers:
    - name: mlflow-wine-classifier
      image: <DOCKER_IMAGE_NAME>
      ports:
        - name: http-metrics  # Add this
          containerPort: 8012
      env:
      - name: PROTOCOL
        value: v2
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"