apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-ingress                 # ◀︎ single entry‐point for all models
  namespace: mlops
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /v2/models/$1/$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # ───── First model: wine-classifier ─────
      - path: /models/mlflow-wine-classifier/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: mlflow-wine-classifier-predictor-default
            port:
              number: 80
      # ───── Add future models here (copy-paste) ─────
      # - path: /models/another-model/(.*)
      #   ...
