primary:
  # Exactly the user & DB that MLflow will use
  postgresqlUsername: mlflow
  postgresqlPassword: student
  postgresqlDatabase: mlflow

  persistence:
    enabled: true
    storageClass: local-path
    size: 10Gi

service:
  type: ClusterIP
  
