primary:
  postgresqlUsername: mlflow
  postgresqlPassword: "${POSTGRES_PASSWORD}"
  postgresqlDatabase: mlflow

  persistence:
    enabled: true
    storageClass: local-path
    size: 10Gi

service:
  type: ClusterIP
