# services/monitoring/inference-service-monitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wine-classifier-monitor
  namespace: mlops
  labels:
    release: prometheus
spec:
  # THE FINAL FIX: This combination of stable labels ensures that any
  # new revision of this model's predictor will be automatically discovered.
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: mlflow-wine-classifier
      networking.internal.knative.dev/serviceType: Private
      component: predictor
  
  namespaceSelector:
    matchNames:
    - mlops

  endpoints:
  - port: http-usermetric
    path: /metrics
    interval: 15s