apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mlflow-wine-classifier-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  jobLabel: kserve-metrics
  namespaceSelector:
    matchNames: [mlops]
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: mlflow-wine-classifier
  endpoints:
  - port: http-metrics  # Matches port name in InferenceService
    path: /metrics
    interval: 15s